### ISSUE TITLE
Error with multiple user in Plex Home

### ISSUE THREAD

**Issue by stian89** [jacobwgillespie/plex-sync#27]
Hi!
I am running two Plex servers in my home network. Both on Windows 10 PCs.

For my admin user, the Plex-sync command works fine with all the different sections.
For my 3 other users, I have problems.

I use this for all 4 users:
`plex-sync` TOKEN@IP1/section `TOKEN/@IP2/section`

When I run it for my 3 other users, I get this error:
`TypeError: Cannot read property 'Video' of undefined
    at C:\Users\PC\AppData\Roaming\npm\node_modules\plex-sync\lib\plex.js:78:40
    at process._tickCallback (internal/process/next_tick.js:103:7)`

I looked at all the other issues here, and found one with the same error.

If I try to open this URL: `http://SERVER_HOST/library/sections/SECTION_NUMBER/allLeaves?X-Plex-Token=PLEX_TOKEN` with any of the 4 tokens (even with the one that syncs OK) and both IP's, I get an error.

I have tried running all the commands in a batch file with a "call-command" to get them all to run one after another. I ran it a copule of times. This resulted in one of the 3 "broken" users to get ONE show synced, while the others remained untouched.

Any suggestions? :)

**Comment by stian89** [comment]
Finally got the allLeaves url to work.
On my token , it makes an xml file.
For the other tokens, I get 401 unauthorized.

**Comment by jacobwgillespie** [comment]
So, you're getting a 401 unauthorized with the combination of library ID and Plex Home user token?  Did you share that particular library with your Plex Home user?  And if so, what kind of Plex Home account is it (existing Plex user, managed user, etc.)?

I am able to sync with my test Plex Home user (managed user) so I think we should be able to figure this out.

I did just release `v0.6.0` that now uses pagination to read the items in the library which might fix your issue, but I would suspect that something else is going on here.

**Comment by stian89** [comment]
Thanks for the respons!
Yeah, any library ID combined with the other users' tokens result in 401 unauthorized. My own token works fine.

All three accounts that I am trying to sync, have their own Plex.tv account (not managed).
I got their tokens by logging in with their user and using the bookmarklet. :)

All three accounts do have access to all libraries. 
I'll try the new version. :)

**Comment by stian89** [comment]
After updating to 0.6.0 i get the following error (highligts of the error I get):

TypeError: Cannot read property '$' of undefined
 at _callee2$ (location/plex.js:110:57)
 at _trycatch (location\runtime.js:6...)
at Generatorfunctionprototype.invoke and prototype..

My account still works.

**Comment by jalarab** [comment]
same problem here. All my users have their own plex.tv account, I have their tokens but I receive the same error message:
TypeError: Cannot read property '$' of undefined
    at _callee2$ (C:\Users\lenovo\AppData\Roaming\npm\node_modules\plex-sync\lib\plex.js:110:57)
    at tryCatch (C:\Users\lenovo\AppData\Roaming\npm\node_modules\plex-sync\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\Users\lenovo\AppData\Roaming\npm\node_modules\plex-sync\node_modules\regenerator-runtime\runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\lenovo\AppData\Roaming\npm\node_modules\plex-sync\node_modules\regenerator-runtime\runtime.js:116:21)
    at step (C:\Users\lenovo\AppData\Roaming\npm\node_modules\plex-sync\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\lenovo\AppData\Roaming\npm\node_modules\plex-sync\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by caldude321** [comment]
FYI, I'm getting this with Managed Accounts.  Works on the primary account; havent tried non-primary plex account.  Version that was downloaded today.

**Comment by thanamatos** [comment]
Getting the same thing downloaded today. Ubuntu 16.04 LTS.  Primary account works.  Plex.tv account errors out.
TypeError: Cannot read property '$' of undefined
    at _callee2$ (/usr/lib/node_modules/plex-sync/lib/plex.js:107:57)
    at tryCatch (/usr/lib/node_modules/plex-sync/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/lib/node_modules/plex-sync/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/lib/node_modules/plex-sync/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/usr/lib/node_modules/plex-sync/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/lib/node_modules/plex-sync/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by cfoucher** [comment]
I was running into the same issue, but fixed it by doing the following:
- In Plex enable debug and verbose logging as well as enable tokens in logs
- Run the command with a known bad token i.e plex-sync <known_bad_token>@<server1>/3,rw <token>@<server2>/2,rw

Grep the Plex Media Server.log file on<server1> for the <known_bad_token> something like "tail -f Plex\ Media\ Server.log | grep <known_bad_token>"

You should then see something like this in the output:
https://plex.tv/servers/<some_long_id_number>/access_tokens.xml?auth_token=<primary_auth_token>&includeProfiles=1&includeProviders=1&unknownToken=<KNOWN_BAD_TOKEN>

Navigating to that url in a browser will list the tokens for each plex.tv account connected to your server. 
Repeating this above for each server you are trying to sync with will get you the proper auth_tokens.
You then just need to match up each users tokens for each server.

**Comment by thanamatos** [comment]
Thanks.  That worked perfectly.

**Comment by jalarab** [comment]
it doesn't work for me. I tried to follow your instructions but I should did something wrong, because I still receiving the same error message.

When I navigate to the url, I can see something like this for each user:
<access_token token="THIS_IS_THE_TOKEN_THAT_I_USE_NOW" username="USER" thumb="https://plex.tv/users/63f71808dca5c41d/avatar?c=2017-04-17+09%3A17%3A42+UTC" title="USER" id="10750" owned="0" allow_sync="1" allow_camera_upload="0" allow_channels="1" filter_all="" filter_movies="" filter_music="" filter_photos="" filter_television="" scrobble_types="">
<profile_settings default_audio_language="es" default_subtitle_language="es" auto_select_subtitle="2" auto_select_audio="1"/>
<library_section key="1"/>
<library_section key="2"/>

but this error appears
TypeError: Cannot read property '$' of undefined
at _callee2$ (/usr/lib/node_modules/plex-sync/lib/plex.js:107:57)
at tryCatch (/usr/lib/node_modules/plex-sync/node_modules/regenerator-runtime/runtime.js:64:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/lib/node_modules/plex-sync/node_modules/regenerator-runtime/runtime.js:299:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/lib/node_modules/plex-sync/node_modules/regenerator-runtime/runtime.js:116:21)
at step (/usr/lib/node_modules/plex-sync/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
at /usr/lib/node_modules/plex-sync/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
at process._tickCallback (internal/process/next_tick.js:109:7)

@cfoucher can you help me? what i been doing wrong?

**Comment by thanamatos** [comment]
What I didn't know was that each user on each server has a different token.  You will need to pull up that xml file that lists all your users and their tokens from each of your servers you are trying to sync.  you can then build the plex-sync command for each user once you get the two tokens each user has.  Just make sure you match the IP with the user token you got from that server in the sync command because if you swap the tokens between the servers its the same as using a bad tokens.  Hopefully that doesn't confuse you more.

**Comment by jacobwgillespie** [comment]
Ooooh, there's an endpoint that retrieves the access tokens of multiple users?  That would make this a lot more user-friendly.  Let me take a look and see if I can get a more automated way of fetching those tokens to work, as that might clear up a lot of smaller issues that people are running into.

**Comment by thanamatos** [comment]
That would be awesome.  You would just need to be able to grab all the xml's from the servers and parse them.  Then match the username from each to match up the tokens.  The only thing is that people would need to enable the option to store the tokens in their log file which is off by default.

**Comment by jacobwgillespie** [comment]
I _think_ I can actually call the Plex API directly, just like the Plex servers are doing - I just determined that the "some long ID number" is the machine identifier from the Plex server response, so I'm going to see if I can add PIN authentication to the `plex-sync` CLI then you should just be able to do `plex-sync login` and it will authenticate and grab all the tokens.  Hopefully.  We'll see if that's possible.

**Comment by jacobwgillespie** [comment]
It works!  I'm able to enumerate all the users who have access to the system, from managed users, Plex Home users, to friends who have share access as well as retrieve all their access tokens for all the different servers they have access to.  Additionally login works with a pin, so `plex-sync` can give you a 4-digit pin to enter into https://plex.tv/pin and it can automatically figure out all the rest.

Do any of you in this thread have any opinions on configuration files (like TOML files)?  Any experience with them?  For the next version of `plex-sync` that incorporates the above improvements, I think it will have officially outgrown its command-line syntax in terms of features, and probably will have to work based on configuration files.  But I'm not sure how familiar people are with something like TOML, or if that would even be the right choice (it's hopefully simpler for people to understand / edit since there's no indentation required).

But I'm envisioning you could create a configuration file that defined your servers, then you could run sync commands on them.

The new flow would be, first login:

```bash
$ plex-sync login
Please visit https://plex.tv/pin in your browser and enter the pin A4C7, then press ENTER. [enter]
You have successfully logged in!
```

Then you would create a config file named `plex-sync.toml` or something:

```toml
# Define two servers

[server.home]
host = "127.0.0.1"

[server.cloud]
plexcloud = "true" # plex-sync can automatically detect your Plex Cloud server

# Sync movies library between two servers

[sync.movies]
progress = true
[sync.movies.home]
server = "home"
library = 4
read = true
write = true
[sync.movies.cloud]
server = "cloud"
library = 2
read = true
write = true

# Sync songs between two servers and different users (you and a Plex home user)

[sync.songs]
progress = true
[sync.songs.home]
server = "home"
user = "me" # the default
library = 1
read = true
write = true
[sync.songs.cloud]
server = "cloud"
user = "home:other-user-name"
library = 3
read = true
write = true

# Sync with rules, to create two individual TV libraries for two users and a common 
# "shared" library that marks watched only when both people watch the same episode:

[sync.tv]
[sync.tv.mine]
server = "home"
user = "me"
library = 1
read = true
write = false
[sync.tv.theirs]
server = "home"
user = "home:other-user-name"
library = 1
read = true
write = false
[sync.tv.common]
server = "home"
user = "home:common-account"
library = 1
read = false
write = true
minOtherServers = 2

# A complementing sync that marks two libraries as watched when the 
# common library is watched:

[sync.tv_common]
[sync.tv_common.mine]
server = "home"
user = "me"
library = 1
read = false
write = true
[sync.tv_common.theirs]
server = "home"
user = "home:other-user-name"
library = 1
read = false
write = true
[sync.tv_common.common]
server = "home"
user = "home:common-account"
library = 1
read = true
write = false

# Syncing multiple libraries by ID (1 and 2, 5 and 1, 6 and 6):

[sync.multiple]
[sync.multiple.mine]
server = "home"
library = [1, 5, 6]
read = true
write = true
[sync.multiple.theirs]
server = "cloud"
library = [2, 1, 6]
read = true
write = true
```

Then executing those syncs would be as simple as:

```bash
$ plex-sync sync multiple
$ plex-sync sync tv tv_common
$ plex-sync sync songs
$ plex-sync sync movies
```

Thoughts?  Does that seem useful, or do you all have any other ideas?
